{%- from "nginx/map.jinja" import server, monitoring with context %}
{%- if server.get('enabled', False) %}
server:
  alert:
    NginxServiceDown:
      if: >-
        nginx_up != 1
      {%- raw %}
      labels:
        severity: minor
        service: nginx
      annotations:
        summary: "NGINX service is down"
        description: "The NGINX service on the {{ $labels.host }} node is down."
      {% endraw %}
    NginxServiceOutage:
      if: >-
        count(label_replace(nginx_up, "cluster", "$1", "host", "([^0-9]+).+")) by (cluster) == count(label_replace(nginx_up == 0, "cluster", "$1", "host", "([^0-9]+).+")) by (cluster)
      {%- raw %}
      labels:
        severity: critical
        service: nginx
      annotations:
        summary: "NGINX cluster outage"
        description: "All NGINX processes within the {{ $labels.cluster }} cluster are down."
      {% endraw %}
    NginxDroppedIncomingConnections:
      if: >-
        irate(nginx_accepts[5m]) - irate(nginx_handled[5m]) > 0
      {%- raw %}
      for: 5m
      labels:
        severity: minor
        service: nginx
      annotations:
        summary: "NGINX drops incoming connections"
        description: "NGINX drops {{ $value }} accepted connections per second for 5 minutes."
      {% endraw %}
{%- endif %}
